% Compute spectrogram

% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 21-Jun-2025 22:46:45

% Parameters
timeLimits = [1.74914e+09 1.749141e+09]; % seconds
frequencyLimits = [0 1000]; % Hz
timeResolution = 0.256; % seconds
overlapPercent = 50;

%%
% Index into signal time region of interest
y_ROI = y(:);
sampleRate = 2000; % Hz
startTime = 1.749136e+09; % seconds
timeValues = startTime + (0:length(y_ROI)-1).'/sampleRate;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
y_ROI = y_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,T] = pspectrum(y_ROI,timeValues, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'TimeResolution',timeResolution, ...
    'OverlapPercent',overlapPercent);
